#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

/**注册Composer自动加载器**/
require __DIR__ . '/vendor/autoload.php';
/**包含Yii类文件**/
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

/**加载应用配置**/
$config = require __DIR__ . '/config/console.php';

//创建，配置，运行一个应用
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
